# Generated by Django 4.1.7 on 2023-04-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_name',
        ),
    ]
