# Generated by Django 4.1.7 on 2023-04-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_person_created_person_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
