# Generated by Django 4.1.7 on 2023-04-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profile_person_profile_picture'),
        ('base', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='sales',
            name='created',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.farmer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='positions',
            field=models.ManyToManyField(to='sales.position'),
        ),
        migrations.AddField(
            model_name='sales',
            name='salesman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sales',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
