# Generated by Django 4.1.7 on 2023-04-06 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csv',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='csv',
            name='file_name',
            field=models.FileField(default=django.utils.timezone.now, upload_to='csvs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
