# Generated by Django 4.1.7 on 2023-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_csv_activated_csv_created_csv_file_name_csv_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
