# Generated by Django 4.1.7 on 2023-04-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produce',
        ),
    ]
